name: CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout del repositorio
      - name: Checkout repository
        uses: actions/checkout@v4

      # Configurar Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # O la versión que prefieras

      # Instalar dependencias necesarias
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt


      # Ejecutar pruebas automatizadas con pytest
      - name: Run tests
        run: |
          pip install pytest
          pytest tests/

      # Opcional: Despliegue continuo
      - name: Deploy
        run: |
          echo "Despliegue continuo..."
          echo "..."
